### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by KMx404** [betaveros/puzzlehunt.net#1]
Hey betaveros, 
Can you please upgrade the README.md file so that Anyone who's interested in this project can Help scaling it. 
You can make a list of methods we can contribute in. 
&& Good luck

**Comment by betaveros** [comment]
I added a README, but I don't really have plans for a list of ways for people to contribute. It's just an expository website. If you are already familiar with puzzlehunts and there's anything you think is missing or incomplete anywhere in the website, you can PR to add it; if you're not, trying to contribute to this website doesn't seem like a terribly fruitful endeavor.
